name: Build and deploy Node.js app to Azure Web App - IntanExplorer

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: npm install and build
        run: |
          npm install
          npm run build

      - name: Zip the application for deployment
        run: |
          zip -r release.zip dist package.json package-lock.json

      - name: Upload dist artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: production # Use lowercase here
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download dist artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: Unzip dist artifact for deployment and show contents
        run: |
          unzip release.zip -d ./deployment/
          ls -l ./deployment/
          
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_096F1C3C31FE473785882ACA40999507 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_A62718C7B3124E9EA7CB927112B0A7FB }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_B6DF977035CC48B18F020BD1E282FD14 }} 

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'asmbc-explorer'
          slot-name: 'production'
          package: ./deployment/
